name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          pip install pytest fastapi httpx
      - name: Run simple tests
        run: pytest test_simple.py -v
      - name: Run API tests
        run: pytest test_api.py -v