name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
      fail-fast: false

    env:
      PYTHONPATH: ${{ github.workspace }}
      DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libpq-dev python3-dev

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel setuptools
        pip install -r requirements.txt

    - name: Show directory structure
      run: |
        echo "Current directory:"
        pwd
        echo "\nDirectory structure:"
        tree
        echo "\nPYTHONPATH:"
        echo $PYTHONPATH
        echo "\nPython sys.path:"
        python -c "import sys; print('\n'.join(sys.path))"

    - name: Create test directories
      run: |
        mkdir -p src/backend/ai/models
        touch src/backend/ai/__init__.py
        touch src/backend/__init__.py
        touch src/__init__.py

    - name: Try importing key modules
      run: |
        python -c "from src.backend.main import app; print('Successfully imported app')"

    - name: Run single test first
      run: |
        python -m pytest tests/test_api.py::test_get_statistics -v --tb=long

    - name: Run all tests
      run: |
        python -m pytest tests/ -v --tb=long
